# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b17881d0318df9186e0c62fda386d589f8a796e652128ddbeeac1c42e778e7a838479cdb59f46e342a47b12fc3818550e57f10d69399ac164866f41825fde4a

test:
  secret_key_base: 4d12ed6c87a09c1c3e486d449019ff577e0ed772fda9a450b9d790d138947967664019f3eda89f4112da60a5c7a9036ff7c1c0aeddd789e64c4072f30a316d86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
